
env:
#  - PUBLISHMETA=True
#  - PUBLISHDOCS=True
# Specify the main Mafile supported goals.
  - GOAL=test
  - GOAL=targets-group-1
  - GOAL=targets-group-2
  - GOAL=targets-group-3
  - GOAL=targets-group-4
  - GOAL=targets-group-rest
#  - GOAL=all
#  - GOAL=AFROMINI
#  - GOAL=AIORACERF3
#  - GOAL=...
# Or specify targets to run.
#  - TARGET=AFROMINI
#  - TARGET=AIORACERF3
#  - TARGET=...

# use new docker environment
sudo: false

git:
  depth: 5

addons:
  apt:
    packages:
      - lcov
      - build-essential
      - git
      - libc6-i386
      - time
      - libblocksruntime-dev

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang
dist: trusty


before_install:
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov

install:
  - make arm_sdk_install

before_script:
  - tools/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc --version
  - clang --version
  - clang++ --version
  - gcc --version

script: ./.travis.sh

cache:
  directories:
  - downloads
  - tools


#notifications:
#  irc: "chat.freenode.net#cleanflight"
#  use_notice: true
#  skip_join: true

notifications:
  slack: betaflightgroup:LQSj02nsBEdefcO5UQcLgB0U
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c20f7a1a7e311499a88
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
